// import renderCellExpand from "../components/datagrid/renderCellExpand";

// Comprehensive report cols - گزارشات جامع
export const reportCols = [
  {
    field: "id",
    headerName: "شناسه",
    width: 0,
    align: "left",
    headerAlign: "right",
    headerClassName: "DatagridHeaderBGC",
    hideable: false,
  },
  {
    field: "row",
    headerName: "ردیف",
    width: 60,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
  },
  {
    field: "pasdari_code",
    headerName: "کد پاسداری",
    width: 90,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "nationality_code",
    headerName: "کد ملی",
    width: 90,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "name",
    headerName: "نام",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "surname",
    headerName: "نام خانوادگی",
    width: 150,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "fathername",
    headerName: "نام پدر",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "commander",
    headerName: "مقام دستوردهنده/شاکی",
    width: 150,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "tahsili_title",
    headerName: "تحصیلات",
    width: 300,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "vahed_title",
    headerName: "رده خدمتی",
    width: 200,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "jens_title",
    headerName: "جنسیت",
    width: 70,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "ozviat_type_title",
    headerName: "عضویت",
    width: 150,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "rank",
    headerName: "درجه",
    width: 60,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "rotbe_code",
    headerName: "رتبه",
    width: 60,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "title",
    headerName: "نوع عمل ارتکابی",
    width: 150,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "r_reason",
    headerName: "شرح عمل ارتکابی",
    width: 500,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "reason",
    headerName: "عناوین قانونی",
    width: 1000,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "do_date_p",
    headerName: "تاریخ وقوع",
    width: 90,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "type",
    headerName: "نوع اقدام",
    width: 150,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "r_count",
    headerName: "مقدار",
    width: 90,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "audit_ref",
    headerName: "مرجع رسیدگی کننده",
    width: 500,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "hokm",
    headerName: "قرار صادره",
    width: 300,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
];

// گزارشات آماری
export const statisticalReportCols = [
  {
    field: "id",
    headerName: "شناسه",
    width: 0,
    align: "left",
    headerAlign: "right",
    headerClassName: "DatagridHeaderBGC",
    hideable: false,
  },
  {
    field: "title",
    headerName: "عنوان رده",
    width: 400,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
  },
  {
    field: "sardari",
    headerName: "سرداری",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "afsar_arshad",
    headerName: "افسری ارشد",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "afsar_joz",
    headerName: "افسر جزء",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "daraje_dar",
    headerName: "درجه‌دار",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "man",
    headerName: "کارمند (برادر)",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "woman",
    headerName: "کارمند (خواهر)",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "basiji",
    headerName: "بسیجی",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "peymani_nezami",
    headerName: "پیمانی نظامی",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "peymani_karmand",
    headerName: "پیمانی کارمند",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "mohasel",
    headerName: "محصل",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "kharid_khedmat",
    headerName: "خرید خدمت",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "sarbaz",
    headerName: "سرباز",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "sarbaz_darajeDar",
    headerName: "سربازدرجه‌دار",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "sarbaz_afsar",
    headerName: "سربازافسر",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
  {
    field: "total",
    headerName: "جمع",
    width: 100,
    align: "center",
    headerAlign: "center",
    headerClassName: "DatagridHeaderBGC",
    // renderCell: renderCellExpand,
  },
];
