// applauses columns mapping
module.exports = {
  applausesColsMapping: {
    row: "(@row_number := @row_number + 1)",
    parvandeCode: "applauser_parvande_code",
    name: "applauser_surname",
    nationalCode: "applauser_nationality_code",
    recommender: "recommender_surname",
    commander: "commander_surname",
    applauseType: "applause_type_description",
    applauseDescription: "applause_description",
    applauseDate: "applause_date",
    status: "applause_status",
  },
  punishmentsColsMapping: {
    row: "(@row_number := @row_number + 1)",
    parvandeCode: "punishment_subject_parvande_code",
    name: "punishment_subject_surname",
    nationalCode: "punishment_subject_nationality_code",
    recommender: "punishment_recommender_surname",
    commander: "punishment_commander_surname",
    punishmentTypeDescription: "punishments_type_description",
    punishmentDescription: "punishment_description",
    punishmentDate: "punishment_date",
    status: "punishment_status",
  },
  crimesColsMapping: {
    row: "(@row_number := @row_number + 1)",
    parvandeCode: "crimes_mojrem_parvande_code",
    name: "crimes_mojrem_surname",
    nationalCode: "crimes_mojrem_nationality_code",
    shaki: "crimes_shaki_surname",
    shakiNumber: "crimes_shaki_number",
    crimeType: "crimes_crime_type",
    issuedVerdict: "crimes_issued_hokm",
    crimeOccuranceDate: "crimes_jorm_occurance_date",
    status: "crime_status",
  },
  remarksColsMapping: {
    row: "(@row_number := @row_number + 1)",
    parvandeCode: "remark_subject_parvande_code",
    name: "remark_subject_surname",
    nationalCode: "remark_subject_nationality_code",
    recommender: "remark_recommender_surname",
    commander: "remark_commander_surname",
    remarkTypeDescription: "remark_type_title",
    remarkDescription: "remark_description",
    remarkDate: "remark_date",
    status: "remark_status",
  },
};
